export interface DraymanSuperset {
    /**
     * Superset instance URL, including protocol.
     */
    supersetDomain: string;
    /**
     * Embed identifier generated by the Superset embedding UI.
     */
    embedId: string;
    /**
     * Called by the element when Superset needs a guest token.
     */
    onFetchGuestToken: ElementEvent<{}>;
    /**
     * Dashboard UI configuration passed to the Superset Embedded SDK.
     */
    dashboardUiConfig?: {
        hideTitle?: boolean;
        hideTab?: boolean;
        hideChartControls?: boolean;
        filters?: {
            [key: string]: boolean | undefined;
            visible?: boolean;
            expanded?: boolean;
        };
        urlParams?: {
            [key: string]: string | number | boolean;
        };
    };
    /**
     * Additional iframe sandbox permissions.
     */
    iframeSandboxExtras?: string[];
    /**
     * Referrer policy applied to the embedded iframe request.
     */
    referrerPolicy?: ReferrerPolicy;
}